/**
 * Local Reference Data for Company Code Management
 * Contains countries, currencies, and languages data to avoid external API dependencies
 */

const referenceData = {
    countries: [
        { code: 'AD', name: 'Andorra', capital: 'Andorra la Vella', currency: 'EUR', language: 'CA' },
        { code: 'AE', name: 'United Arab Emirates', capital: 'Abu Dhabi', currency: 'AED', language: 'AR' },
        { code: 'AF', name: 'Afghanistan', capital: 'Kabul', currency: 'AFN', language: 'FA' },
        { code: 'AG', name: 'Antigua and Barbuda', capital: "Saint John's", currency: 'XCD', language: 'EN' },
        { code: 'AI', name: 'Anguilla', capital: 'The Valley', currency: 'XCD', language: 'EN' },
        { code: 'AL', name: 'Albania', capital: 'Tirana', currency: 'ALL', language: 'SQ' },
        { code: 'AM', name: 'Armenia', capital: 'Yerevan', currency: 'AMD', language: 'HY' },
        { code: 'AO', name: 'Angola', capital: 'Luanda', currency: 'AOA', language: 'PT' },
        { code: 'AQ', name: 'Antarctica', capital: '', currency: '', language: 'EN' },
        { code: 'AR', name: 'Argentina', capital: 'Buenos Aires', currency: 'ARS', language: 'ES' },
        { code: 'AS', name: 'American Samoa', capital: 'Pago Pago', currency: 'USD', language: 'EN' },
        { code: 'AT', name: 'Austria', capital: 'Vienna', currency: 'EUR', language: 'DE' },
        { code: 'AU', name: 'Australia', capital: 'Canberra', currency: 'AUD', language: 'EN' },
        { code: 'AW', name: 'Aruba', capital: 'Oranjestad', currency: 'AWG', language: 'NL' },
        { code: 'AX', name: 'Åland Islands', capital: 'Mariehamn', currency: 'EUR', language: 'SV' },
        { code: 'AZ', name: 'Azerbaijan', capital: 'Baku', currency: 'AZN', language: 'AZ' },
        { code: 'BA', name: 'Bosnia and Herzegovina', capital: 'Sarajevo', currency: 'BAM', language: 'BS' },
        { code: 'BB', name: 'Barbados', capital: 'Bridgetown', currency: 'BBD', language: 'EN' },
        { code: 'BD', name: 'Bangladesh', capital: 'Dhaka', currency: 'BDT', language: 'BN' },
        { code: 'BE', name: 'Belgium', capital: 'Brussels', currency: 'EUR', language: 'NL' },
        { code: 'BF', name: 'Burkina Faso', capital: 'Ouagadougou', currency: 'XOF', language: 'FR' },
        { code: 'BG', name: 'Bulgaria', capital: 'Sofia', currency: 'BGN', language: 'BG' },
        { code: 'BH', name: 'Bahrain', capital: 'Manama', currency: 'BHD', language: 'AR' },
        { code: 'BI', name: 'Burundi', capital: 'Gitega', currency: 'BIF', language: 'FR' },
        { code: 'BJ', name: 'Benin', capital: 'Porto-Novo', currency: 'XOF', language: 'FR' },
        { code: 'BL', name: 'Saint Barthélemy', capital: 'Gustavia', currency: 'EUR', language: 'FR' },
        { code: 'BM', name: 'Bermuda', capital: 'Hamilton', currency: 'BMD', language: 'EN' },
        { code: 'BN', name: 'Brunei', capital: 'Bandar Seri Begawan', currency: 'BND', language: 'MS' },
        { code: 'BO', name: 'Bolivia', capital: 'Sucre', currency: 'BOB', language: 'ES' },
        { code: 'BQ', name: 'Caribbean Netherlands', capital: 'Kralendijk', currency: 'USD', language: 'NL' },
        { code: 'BR', name: 'Brazil', capital: 'Brasília', currency: 'BRL', language: 'PT' },
        { code: 'BS', name: 'Bahamas', capital: 'Nassau', currency: 'BSD', language: 'EN' },
        { code: 'BT', name: 'Bhutan', capital: 'Thimphu', currency: 'BTN', language: 'DZ' },
        { code: 'BV', name: 'Bouvet Island', capital: '', currency: 'NOK', language: 'NO' },
        { code: 'BW', name: 'Botswana', capital: 'Gaborone', currency: 'BWP', language: 'EN' },
        { code: 'BY', name: 'Belarus', capital: 'Minsk', currency: 'BYN', language: 'BE' },
        { code: 'BZ', name: 'Belize', capital: 'Belmopan', currency: 'BZD', language: 'EN' },
        { code: 'CA', name: 'Canada', capital: 'Ottawa', currency: 'CAD', language: 'EN' },
        { code: 'CC', name: 'Cocos Islands', capital: 'West Island', currency: 'AUD', language: 'EN' },
        { code: 'CD', name: 'DR Congo', capital: 'Kinshasa', currency: 'CDF', language: 'FR' },
        { code: 'CF', name: 'Central African Republic', capital: 'Bangui', currency: 'XAF', language: 'FR' },
        { code: 'CG', name: 'Republic of the Congo', capital: 'Brazzaville', currency: 'XAF', language: 'FR' },
        { code: 'CH', name: 'Switzerland', capital: 'Bern', currency: 'CHF', language: 'DE' },
        { code: 'CI', name: 'Côte d\'Ivoire', capital: 'Yamoussoukro', currency: 'XOF', language: 'FR' },
        { code: 'CK', name: 'Cook Islands', capital: 'Avarua', currency: 'NZD', language: 'EN' },
        { code: 'CL', name: 'Chile', capital: 'Santiago', currency: 'CLP', language: 'ES' },
        { code: 'CM', name: 'Cameroon', capital: 'Yaoundé', currency: 'XAF', language: 'EN' },
        { code: 'CN', name: 'China', capital: 'Beijing', currency: 'CNY', language: 'ZH' },
        { code: 'CO', name: 'Colombia', capital: 'Bogotá', currency: 'COP', language: 'ES' },
        { code: 'CR', name: 'Costa Rica', capital: 'San José', currency: 'CRC', language: 'ES' },
        { code: 'CU', name: 'Cuba', capital: 'Havana', currency: 'CUP', language: 'ES' },
        { code: 'CV', name: 'Cape Verde', capital: 'Praia', currency: 'CVE', language: 'PT' },
        { code: 'CW', name: 'Curaçao', capital: 'Willemstad', currency: 'ANG', language: 'NL' },
        { code: 'CX', name: 'Christmas Island', capital: 'Flying Fish Cove', currency: 'AUD', language: 'EN' },
        { code: 'CY', name: 'Cyprus', capital: 'Nicosia', currency: 'EUR', language: 'EL' },
        { code: 'CZ', name: 'Czech Republic', capital: 'Prague', currency: 'CZK', language: 'CS' },
        { code: 'DE', name: 'Germany', capital: 'Berlin', currency: 'EUR', language: 'DE' },
        { code: 'DJ', name: 'Djibouti', capital: 'Djibouti', currency: 'DJF', language: 'FR' },
        { code: 'DK', name: 'Denmark', capital: 'Copenhagen', currency: 'DKK', language: 'DA' },
        { code: 'DM', name: 'Dominica', capital: 'Roseau', currency: 'XCD', language: 'EN' },
        { code: 'DO', name: 'Dominican Republic', capital: 'Santo Domingo', currency: 'DOP', language: 'ES' },
        { code: 'DZ', name: 'Algeria', capital: 'Algiers', currency: 'DZD', language: 'AR' },
        { code: 'EC', name: 'Ecuador', capital: 'Quito', currency: 'USD', language: 'ES' },
        { code: 'EE', name: 'Estonia', capital: 'Tallinn', currency: 'EUR', language: 'ET' },
        { code: 'EG', name: 'Egypt', capital: 'Cairo', currency: 'EGP', language: 'AR' },
        { code: 'EH', name: 'Western Sahara', capital: 'El Aaiún', currency: 'MAD', language: 'AR' },
        { code: 'ER', name: 'Eritrea', capital: 'Asmara', currency: 'ERN', language: 'TI' },
        { code: 'ES', name: 'Spain', capital: 'Madrid', currency: 'EUR', language: 'ES' },
        { code: 'ET', name: 'Ethiopia', capital: 'Addis Ababa', currency: 'ETB', language: 'AM' },
        { code: 'FI', name: 'Finland', capital: 'Helsinki', currency: 'EUR', language: 'FI' },
        { code: 'FJ', name: 'Fiji', capital: 'Suva', currency: 'FJD', language: 'EN' },
        { code: 'FK', name: 'Falkland Islands', capital: 'Stanley', currency: 'FKP', language: 'EN' },
        { code: 'FM', name: 'Micronesia', capital: 'Palikir', currency: 'USD', language: 'EN' },
        { code: 'FO', name: 'Faroe Islands', capital: 'Tórshavn', currency: 'DKK', language: 'FO' },
        { code: 'FR', name: 'France', capital: 'Paris', currency: 'EUR', language: 'FR' },
        { code: 'GA', name: 'Gabon', capital: 'Libreville', currency: 'XAF', language: 'FR' },
        { code: 'GB', name: 'United Kingdom', capital: 'London', currency: 'GBP', language: 'EN' },
        { code: 'GD', name: 'Grenada', capital: "Saint George's", currency: 'XCD', language: 'EN' },
        { code: 'GE', name: 'Georgia', capital: 'Tbilisi', currency: 'GEL', language: 'KA' },
        { code: 'GF', name: 'French Guiana', capital: 'Cayenne', currency: 'EUR', language: 'FR' },
        { code: 'GG', name: 'Guernsey', capital: 'Saint Peter Port', currency: 'GBP', language: 'EN' },
        { code: 'GH', name: 'Ghana', capital: 'Accra', currency: 'GHS', language: 'EN' },
        { code: 'GI', name: 'Gibraltar', capital: 'Gibraltar', currency: 'GIP', language: 'EN' },
        { code: 'GL', name: 'Greenland', capital: 'Nuuk', currency: 'DKK', language: 'KL' },
        { code: 'GM', name: 'Gambia', capital: 'Banjul', currency: 'GMD', language: 'EN' },
        { code: 'GN', name: 'Guinea', capital: 'Conakry', currency: 'GNF', language: 'FR' },
        { code: 'GP', name: 'Guadeloupe', capital: 'Basse-Terre', currency: 'EUR', language: 'FR' },
        { code: 'GQ', name: 'Equatorial Guinea', capital: 'Malabo', currency: 'XAF', language: 'ES' },
        { code: 'GR', name: 'Greece', capital: 'Athens', currency: 'EUR', language: 'EL' },
        { code: 'GS', name: 'South Georgia', capital: 'Grytviken', currency: 'GBP', language: 'EN' },
        { code: 'GT', name: 'Guatemala', capital: 'Guatemala City', currency: 'GTQ', language: 'ES' },
        { code: 'GU', name: 'Guam', capital: 'Hagåtña', currency: 'USD', language: 'EN' },
        { code: 'GW', name: 'Guinea-Bissau', capital: 'Bissau', currency: 'XOF', language: 'PT' },
        { code: 'GY', name: 'Guyana', capital: 'Georgetown', currency: 'GYD', language: 'EN' },
        { code: 'HK', name: 'Hong Kong', capital: 'City of Victoria', currency: 'HKD', language: 'ZH' },
        { code: 'HM', name: 'Heard Island and McDonald Islands', capital: '', currency: 'AUD', language: 'EN' },
        { code: 'HN', name: 'Honduras', capital: 'Tegucigalpa', currency: 'HNL', language: 'ES' },
        { code: 'HR', name: 'Croatia', capital: 'Zagreb', currency: 'EUR', language: 'HR' },
        { code: 'HT', name: 'Haiti', capital: 'Port-au-Prince', currency: 'HTG', language: 'FR' },
        { code: 'HU', name: 'Hungary', capital: 'Budapest', currency: 'HUF', language: 'HU' },
        { code: 'ID', name: 'Indonesia', capital: 'Jakarta', currency: 'IDR', language: 'ID' },
        { code: 'IE', name: 'Ireland', capital: 'Dublin', currency: 'EUR', language: 'EN' },
        { code: 'IL', name: 'Israel', capital: 'Jerusalem', currency: 'ILS', language: 'HE' },
        { code: 'IM', name: 'Isle of Man', capital: 'Douglas', currency: 'GBP', language: 'EN' },
        { code: 'IN', name: 'India', capital: 'New Delhi', currency: 'INR', language: 'HI' },
        { code: 'IO', name: 'British Indian Ocean Territory', capital: 'Diego Garcia', currency: 'USD', language: 'EN' },
        { code: 'IQ', name: 'Iraq', capital: 'Baghdad', currency: 'IQD', language: 'AR' },
        { code: 'IR', name: 'Iran', capital: 'Tehran', currency: 'IRR', language: 'FA' },
        { code: 'IS', name: 'Iceland', capital: 'Reykjavik', currency: 'ISK', language: 'IS' },
        { code: 'IT', name: 'Italy', capital: 'Rome', currency: 'EUR', language: 'IT' },
        { code: 'JE', name: 'Jersey', capital: 'Saint Helier', currency: 'GBP', language: 'EN' },
        { code: 'JM', name: 'Jamaica', capital: 'Kingston', currency: 'JMD', language: 'EN' },
        { code: 'JO', name: 'Jordan', capital: 'Amman', currency: 'JOD', language: 'AR' },
        { code: 'JP', name: 'Japan', capital: 'Tokyo', currency: 'JPY', language: 'JA' },
        { code: 'KE', name: 'Kenya', capital: 'Nairobi', currency: 'KES', language: 'EN' },
        { code: 'KG', name: 'Kyrgyzstan', capital: 'Bishkek', currency: 'KGS', language: 'KY' },
        { code: 'KH', name: 'Cambodia', capital: 'Phnom Penh', currency: 'KHR', language: 'KM' },
        { code: 'KI', name: 'Kiribati', capital: 'South Tarawa', currency: 'AUD', language: 'EN' },
        { code: 'KM', name: 'Comoros', capital: 'Moroni', currency: 'KMF', language: 'AR' },
        { code: 'KN', name: 'Saint Kitts and Nevis', capital: 'Basseterre', currency: 'XCD', language: 'EN' },
        { code: 'KP', name: 'North Korea', capital: 'Pyongyang', currency: 'KPW', language: 'KO' },
        { code: 'KR', name: 'South Korea', capital: 'Seoul', currency: 'KRW', language: 'KO' },
        { code: 'KW', name: 'Kuwait', capital: 'Kuwait City', currency: 'KWD', language: 'AR' },
        { code: 'KY', name: 'Cayman Islands', capital: 'George Town', currency: 'KYD', language: 'EN' },
        { code: 'KZ', name: 'Kazakhstan', capital: 'Nur-Sultan', currency: 'KZT', language: 'KK' },
        { code: 'LA', name: 'Laos', capital: 'Vientiane', currency: 'LAK', language: 'LO' },
        { code: 'LB', name: 'Lebanon', capital: 'Beirut', currency: 'LBP', language: 'AR' },
        { code: 'LC', name: 'Saint Lucia', capital: 'Castries', currency: 'XCD', language: 'EN' },
        { code: 'LI', name: 'Liechtenstein', capital: 'Vaduz', currency: 'CHF', language: 'DE' },
        { code: 'LK', name: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte', currency: 'LKR', language: 'SI' },
        { code: 'LR', name: 'Liberia', capital: 'Monrovia', currency: 'LRD', language: 'EN' },
        { code: 'LS', name: 'Lesotho', capital: 'Maseru', currency: 'LSL', language: 'EN' },
        { code: 'LT', name: 'Lithuania', capital: 'Vilnius', currency: 'EUR', language: 'LT' },
        { code: 'LU', name: 'Luxembourg', capital: 'Luxembourg', currency: 'EUR', language: 'LB' },
        { code: 'LV', name: 'Latvia', capital: 'Riga', currency: 'EUR', language: 'LV' },
        { code: 'LY', name: 'Libya', capital: 'Tripoli', currency: 'LYD', language: 'AR' },
        { code: 'MA', name: 'Morocco', capital: 'Rabat', currency: 'MAD', language: 'AR' },
        { code: 'MC', name: 'Monaco', capital: 'Monaco', currency: 'EUR', language: 'FR' },
        { code: 'MD', name: 'Moldova', capital: 'Chișinău', currency: 'MDL', language: 'RO' },
        { code: 'ME', name: 'Montenegro', capital: 'Podgorica', currency: 'EUR', language: 'SR' },
        { code: 'MF', name: 'Saint Martin', capital: 'Marigot', currency: 'EUR', language: 'FR' },
        { code: 'MG', name: 'Madagascar', capital: 'Antananarivo', currency: 'MGA', language: 'FR' },
        { code: 'MH', name: 'Marshall Islands', capital: 'Majuro', currency: 'USD', language: 'EN' },
        { code: 'MK', name: 'North Macedonia', capital: 'Skopje', currency: 'MKD', language: 'MK' },
        { code: 'ML', name: 'Mali', capital: 'Bamako', currency: 'XOF', language: 'FR' },
        { code: 'MM', name: 'Myanmar', capital: 'Naypyidaw', currency: 'MMK', language: 'MY' },
        { code: 'MN', name: 'Mongolia', capital: 'Ulaanbaatar', currency: 'MNT', language: 'MN' },
        { code: 'MO', name: 'Macao', capital: '', currency: 'MOP', language: 'ZH' },
        { code: 'MP', name: 'Northern Mariana Islands', capital: 'Saipan', currency: 'USD', language: 'EN' },
        { code: 'MQ', name: 'Martinique', capital: 'Fort-de-France', currency: 'EUR', language: 'FR' },
        { code: 'MR', name: 'Mauritania', capital: 'Nouakchott', currency: 'MRU', language: 'AR' },
        { code: 'MS', name: 'Montserrat', capital: 'Plymouth', currency: 'XCD', language: 'EN' },
        { code: 'MT', name: 'Malta', capital: 'Valletta', currency: 'EUR', language: 'MT' },
        { code: 'MU', name: 'Mauritius', capital: 'Port Louis', currency: 'MUR', language: 'EN' },
        { code: 'MV', name: 'Maldives', capital: 'Malé', currency: 'MVR', language: 'DV' },
        { code: 'MW', name: 'Malawi', capital: 'Lilongwe', currency: 'MWK', language: 'EN' },
        { code: 'MX', name: 'Mexico', capital: 'Mexico City', currency: 'MXN', language: 'ES' },
        { code: 'MY', name: 'Malaysia', capital: 'Kuala Lumpur', currency: 'MYR', language: 'MS' },
        { code: 'MZ', name: 'Mozambique', capital: 'Maputo', currency: 'MZN', language: 'PT' },
        { code: 'NA', name: 'Namibia', capital: 'Windhoek', currency: 'NAD', language: 'EN' },
        { code: 'NC', name: 'New Caledonia', capital: 'Nouméa', currency: 'XPF', language: 'FR' },
        { code: 'NE', name: 'Niger', capital: 'Niamey', currency: 'XOF', language: 'FR' },
        { code: 'NF', name: 'Norfolk Island', capital: 'Kingston', currency: 'AUD', language: 'EN' },
        { code: 'NG', name: 'Nigeria', capital: 'Abuja', currency: 'NGN', language: 'EN' },
        { code: 'NI', name: 'Nicaragua', capital: 'Managua', currency: 'NIO', language: 'ES' },
        { code: 'NL', name: 'Netherlands', capital: 'Amsterdam', currency: 'EUR', language: 'NL' },
        { code: 'NO', name: 'Norway', capital: 'Oslo', currency: 'NOK', language: 'NO' },
        { code: 'NP', name: 'Nepal', capital: 'Kathmandu', currency: 'NPR', language: 'NE' },
        { code: 'NR', name: 'Nauru', capital: 'Yaren', currency: 'AUD', language: 'EN' },
        { code: 'NU', name: 'Niue', capital: 'Alofi', currency: 'NZD', language: 'EN' },
        { code: 'NZ', name: 'New Zealand', capital: 'Wellington', currency: 'NZD', language: 'EN' },
        { code: 'OM', name: 'Oman', capital: 'Muscat', currency: 'OMR', language: 'AR' },
        { code: 'PA', name: 'Panama', capital: 'Panama City', currency: 'PAB', language: 'ES' },
        { code: 'PE', name: 'Peru', capital: 'Lima', currency: 'PEN', language: 'ES' },
        { code: 'PF', name: 'French Polynesia', capital: 'Papeete', currency: 'XPF', language: 'FR' },
        { code: 'PG', name: 'Papua New Guinea', capital: 'Port Moresby', currency: 'PGK', language: 'EN' },
        { code: 'PH', name: 'Philippines', capital: 'Manila', currency: 'PHP', language: 'TL' },
        { code: 'PK', name: 'Pakistan', capital: 'Islamabad', currency: 'PKR', language: 'UR' },
        { code: 'PL', name: 'Poland', capital: 'Warsaw', currency: 'PLN', language: 'PL' },
        { code: 'PM', name: 'Saint Pierre and Miquelon', capital: 'Saint-Pierre', currency: 'EUR', language: 'FR' },
        { code: 'PN', name: 'Pitcairn Islands', capital: 'Adamstown', currency: 'NZD', language: 'EN' },
        { code: 'PR', name: 'Puerto Rico', capital: 'San Juan', currency: 'USD', language: 'ES' },
        { code: 'PS', name: 'Palestine', capital: 'Ramallah', currency: 'ILS', language: 'AR' },
        { code: 'PT', name: 'Portugal', capital: 'Lisbon', currency: 'EUR', language: 'PT' },
        { code: 'PW', name: 'Palau', capital: 'Ngerulmud', currency: 'USD', language: 'EN' },
        { code: 'PY', name: 'Paraguay', capital: 'Asunción', currency: 'PYG', language: 'ES' },
        { code: 'QA', name: 'Qatar', capital: 'Doha', currency: 'QAR', language: 'AR' },
        { code: 'RE', name: 'Réunion', capital: 'Saint-Denis', currency: 'EUR', language: 'FR' },
        { code: 'RO', name: 'Romania', capital: 'Bucharest', currency: 'RON', language: 'RO' },
        { code: 'RS', name: 'Serbia', capital: 'Belgrade', currency: 'RSD', language: 'SR' },
        { code: 'RU', name: 'Russia', capital: 'Moscow', currency: 'RUB', language: 'RU' },
        { code: 'RW', name: 'Rwanda', capital: 'Kigali', currency: 'RWF', language: 'RW' },
        { code: 'SA', name: 'Saudi Arabia', capital: 'Riyadh', currency: 'SAR', language: 'AR' },
        { code: 'SB', name: 'Solomon Islands', capital: 'Honiara', currency: 'SBD', language: 'EN' },
        { code: 'SC', name: 'Seychelles', capital: 'Victoria', currency: 'SCR', language: 'EN' },
        { code: 'SD', name: 'Sudan', capital: 'Khartoum', currency: 'SDG', language: 'AR' },
        { code: 'SE', name: 'Sweden', capital: 'Stockholm', currency: 'SEK', language: 'SV' },
        { code: 'SG', name: 'Singapore', capital: 'Singapore', currency: 'SGD', language: 'EN' },
        { code: 'SH', name: 'Saint Helena', capital: 'Jamestown', currency: 'SHP', language: 'EN' },
        { code: 'SI', name: 'Slovenia', capital: 'Ljubljana', currency: 'EUR', language: 'SL' },
        { code: 'SJ', name: 'Svalbard and Jan Mayen', capital: 'Longyearbyen', currency: 'NOK', language: 'NO' },
        { code: 'SK', name: 'Slovakia', capital: 'Bratislava', currency: 'EUR', language: 'SK' },
        { code: 'SL', name: 'Sierra Leone', capital: 'Freetown', currency: 'SLE', language: 'EN' },
        { code: 'SM', name: 'San Marino', capital: 'San Marino', currency: 'EUR', language: 'IT' },
        { code: 'SN', name: 'Senegal', capital: 'Dakar', currency: 'XOF', language: 'FR' },
        { code: 'SO', name: 'Somalia', capital: 'Mogadishu', currency: 'SOS', language: 'SO' },
        { code: 'SR', name: 'Suriname', capital: 'Paramaribo', currency: 'SRD', language: 'NL' },
        { code: 'SS', name: 'South Sudan', capital: 'Juba', currency: 'SSP', language: 'EN' },
        { code: 'ST', name: 'São Tomé and Príncipe', capital: 'São Tomé', currency: 'STN', language: 'PT' },
        { code: 'SV', name: 'El Salvador', capital: 'San Salvador', currency: 'USD', language: 'ES' },
        { code: 'SX', name: 'Sint Maarten', capital: 'Philipsburg', currency: 'ANG', language: 'NL' },
        { code: 'SY', name: 'Syria', capital: 'Damascus', currency: 'SYP', language: 'AR' },
        { code: 'SZ', name: 'Eswatini', capital: 'Mbabane', currency: 'SZL', language: 'EN' },
        { code: 'TC', name: 'Turks and Caicos Islands', capital: 'Cockburn Town', currency: 'USD', language: 'EN' },
        { code: 'TD', name: 'Chad', capital: "N'Djamena", currency: 'XAF', language: 'FR' },
        { code: 'TF', name: 'French Southern Territories', capital: 'Port-aux-Français', currency: 'EUR', language: 'FR' },
        { code: 'TG', name: 'Togo', capital: 'Lomé', currency: 'XOF', language: 'FR' },
        { code: 'TH', name: 'Thailand', capital: 'Bangkok', currency: 'THB', language: 'TH' },
        { code: 'TJ', name: 'Tajikistan', capital: 'Dushanbe', currency: 'TJS', language: 'TG' },
        { code: 'TK', name: 'Tokelau', capital: 'Fakaofo', currency: 'NZD', language: 'EN' },
        { code: 'TL', name: 'East Timor', capital: 'Dili', currency: 'USD', language: 'PT' },
        { code: 'TM', name: 'Turkmenistan', capital: 'Ashgabat', currency: 'TMT', language: 'TK' },
        { code: 'TN', name: 'Tunisia', capital: 'Tunis', currency: 'TND', language: 'AR' },
        { code: 'TO', name: 'Tonga', capital: "Nuku'alofa", currency: 'TOP', language: 'EN' },
        { code: 'TR', name: 'Turkey', capital: 'Ankara', currency: 'TRY', language: 'TR' },
        { code: 'TT', name: 'Trinidad and Tobago', capital: 'Port of Spain', currency: 'TTD', language: 'EN' },
        { code: 'TV', name: 'Tuvalu', capital: 'Funafuti', currency: 'AUD', language: 'EN' },
        { code: 'TW', name: 'Taiwan', capital: 'Taipei', currency: 'TWD', language: 'ZH' },
        { code: 'TZ', name: 'Tanzania', capital: 'Dodoma', currency: 'TZS', language: 'SW' },
        { code: 'UA', name: 'Ukraine', capital: 'Kyiv', currency: 'UAH', language: 'UK' },
        { code: 'UG', name: 'Uganda', capital: 'Kampala', currency: 'UGX', language: 'EN' },
        { code: 'UM', name: 'United States Minor Outlying Islands', capital: '', currency: 'USD', language: 'EN' },
        { code: 'US', name: 'United States', capital: 'Washington, D.C.', currency: 'USD', language: 'EN' },
        { code: 'UY', name: 'Uruguay', capital: 'Montevideo', currency: 'UYU', language: 'ES' },
        { code: 'UZ', name: 'Uzbekistan', capital: 'Tashkent', currency: 'UZS', language: 'UZ' },
        { code: 'VA', name: 'Vatican City', capital: 'Vatican City', currency: 'EUR', language: 'IT' },
        { code: 'VC', name: 'Saint Vincent and the Grenadines', capital: 'Kingstown', currency: 'XCD', language: 'EN' },
        { code: 'VE', name: 'Venezuela', capital: 'Caracas', currency: 'VES', language: 'ES' },
        { code: 'VG', name: 'British Virgin Islands', capital: 'Road Town', currency: 'USD', language: 'EN' },
        { code: 'VI', name: 'United States Virgin Islands', capital: 'Charlotte Amalie', currency: 'USD', language: 'EN' },
        { code: 'VN', name: 'Vietnam', capital: 'Hanoi', currency: 'VND', language: 'VI' },
        { code: 'VU', name: 'Vanuatu', capital: 'Port Vila', currency: 'VUV', language: 'BI' },
        { code: 'WF', name: 'Wallis and Futuna', capital: 'Mata-Utu', currency: 'XPF', language: 'FR' },
        { code: 'WS', name: 'Samoa', capital: 'Apia', currency: 'WST', language: 'SM' },
        { code: 'XK', name: 'Kosovo', capital: 'Pristina', currency: 'EUR', language: 'SQ' },
        { code: 'YE', name: 'Yemen', capital: "Sana'a", currency: 'YER', language: 'AR' },
        { code: 'YT', name: 'Mayotte', capital: 'Mamoudzou', currency: 'EUR', language: 'FR' },
        { code: 'ZA', name: 'South Africa', capital: 'Cape Town', currency: 'ZAR', language: 'EN' },
        { code: 'ZM', name: 'Zambia', capital: 'Lusaka', currency: 'ZMW', language: 'EN' },
        { code: 'ZW', name: 'Zimbabwe', capital: 'Harare', currency: 'ZWL', language: 'EN' }
    ],

    currencies: [
        { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'د.إ' },
        { code: 'AFN', name: 'Afghan Afghani', symbol: '؋' },
        { code: 'ALL', name: 'Albanian Lek', symbol: 'L' },
        { code: 'AMD', name: 'Armenian Dram', symbol: '֏' },
        { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
        { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz' },
        { code: 'ARS', name: 'Argentine Peso', symbol: '$' },
        { code: 'AUD', name: 'Australian Dollar', symbol: '$' },
        { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ' },
        { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼' },
        { code: 'BAM', name: 'Bosnia and Herzegovina Convertible Mark', symbol: 'KM' },
        { code: 'BBD', name: 'Barbadian Dollar', symbol: '$' },
        { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
        { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв' },
        { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب' },
        { code: 'BIF', name: 'Burundian Franc', symbol: 'Fr' },
        { code: 'BMD', name: 'Bermudian Dollar', symbol: '$' },
        { code: 'BND', name: 'Brunei Dollar', symbol: '$' },
        { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.' },
        { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
        { code: 'BSD', name: 'Bahamian Dollar', symbol: '$' },
        { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.' },
        { code: 'BWP', name: 'Botswanan Pula', symbol: 'P' },
        { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br' },
        { code: 'BZD', name: 'Belize Dollar', symbol: '$' },
        { code: 'CAD', name: 'Canadian Dollar', symbol: '$' },
        { code: 'CDF', name: 'Congolese Franc', symbol: 'Fr' },
        { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr' },
        { code: 'CLP', name: 'Chilean Peso', symbol: '$' },
        { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
        { code: 'COP', name: 'Colombian Peso', symbol: '$' },
        { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡' },
        { code: 'CUP', name: 'Cuban Peso', symbol: '$' },
        { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$' },
        { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
        { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fr' },
        { code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
        { code: 'DOP', name: 'Dominican Peso', symbol: '$' },
        { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج' },
        { code: 'EGP', name: 'Egyptian Pound', symbol: '£' },
        { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk' },
        { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br' },
        { code: 'EUR', name: 'Euro', symbol: '€' },
        { code: 'FJD', name: 'Fijian Dollar', symbol: '$' },
        { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£' },
        { code: 'GBP', name: 'British Pound Sterling', symbol: '£' },
        { code: 'GEL', name: 'Georgian Lari', symbol: 'ლ' },
        { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵' },
        { code: 'GIP', name: 'Gibraltar Pound', symbol: '£' },
        { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D' },
        { code: 'GNF', name: 'Guinean Franc', symbol: 'Fr' },
        { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q' },
        { code: 'GYD', name: 'Guyanese Dollar', symbol: '$' },
        { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$' },
        { code: 'HNL', name: 'Honduran Lempira', symbol: 'L' },
        { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn' },
        { code: 'HTG', name: 'Haitian Gourde', symbol: 'G' },
        { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
        { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
        { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪' },
        { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
        { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د' },
        { code: 'IRR', name: 'Iranian Rial', symbol: '﷼' },
        { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
        { code: 'JMD', name: 'Jamaican Dollar', symbol: '$' },
        { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا' },
        { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
        { code: 'KES', name: 'Kenyan Shilling', symbol: 'Sh' },
        { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с' },
        { code: 'KHR', name: 'Cambodian Riel', symbol: '៛' },
        { code: 'KMF', name: 'Comorian Franc', symbol: 'Fr' },
        { code: 'KPW', name: 'North Korean Won', symbol: '₩' },
        { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
        { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك' },
        { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$' },
        { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
        { code: 'LAK', name: 'Lao Kip', symbol: '₭' },
        { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل' },
        { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs' },
        { code: 'LRD', name: 'Liberian Dollar', symbol: '$' },
        { code: 'LSL', name: 'Lesotho Loti', symbol: 'L' },
        { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د' },
        { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.' },
        { code: 'MDL', name: 'Moldovan Leu', symbol: 'L' },
        { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar' },
        { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден' },
        { code: 'MMK', name: 'Myanmar Kyat', symbol: 'Ks' },
        { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮' },
        { code: 'MOP', name: 'Macanese Pataca', symbol: 'P' },
        { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM' },
        { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨' },
        { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: '.ރ' },
        { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK' },
        { code: 'MXN', name: 'Mexican Peso', symbol: '$' },
        { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
        { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT' },
        { code: 'NAD', name: 'Namibian Dollar', symbol: '$' },
        { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
        { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$' },
        { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
        { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨' },
        { code: 'NZD', name: 'New Zealand Dollar', symbol: '$' },
        { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.' },
        { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.' },
        { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/' },
        { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K' },
        { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
        { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
        { code: 'PLN', name: 'Polish Złoty', symbol: 'zł' },
        { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲' },
        { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق' },
        { code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
        { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.' },
        { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
        { code: 'RWF', name: 'Rwandan Franc', symbol: 'Fr' },
        { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س' },
        { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$' },
        { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨' },
        { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.' },
        { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
        { code: 'SGD', name: 'Singapore Dollar', symbol: '$' },
        { code: 'SHP', name: 'Saint Helena Pound', symbol: '£' },
        { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le' },
        { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh' },
        { code: 'SRD', name: 'Surinamese Dollar', symbol: '$' },
        { code: 'SSP', name: 'South Sudanese Pound', symbol: '£' },
        { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db' },
        { code: 'SYP', name: 'Syrian Pound', symbol: 'ل.س' },
        { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L' },
        { code: 'THB', name: 'Thai Baht', symbol: '฿' },
        { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ' },
        { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm' },
        { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت' },
        { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$' },
        { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
        { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: '$' },
        { code: 'TVD', name: 'Tuvaluan Dollar', symbol: '$' },
        { code: 'TWD', name: 'New Taiwan Dollar', symbol: '$' },
        { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'Sh' },
        { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
        { code: 'UGX', name: 'Ugandan Shilling', symbol: 'Sh' },
        { code: 'USD', name: 'United States Dollar', symbol: '$' },
        { code: 'UYU', name: 'Uruguayan Peso', symbol: '$' },
        { code: 'UZS', name: 'Uzbekistani Som', symbol: "so'm" },
        { code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S.' },
        { code: 'VND', name: 'Vietnamese Đồng', symbol: '₫' },
        { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt' },
        { code: 'WST', name: 'Samoan Tala', symbol: 'T' },
        { code: 'XAF', name: 'Central African CFA Franc', symbol: 'Fr' },
        { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$' },
        { code: 'XDR', name: 'Special Drawing Rights', symbol: 'SDR' },
        { code: 'XOF', name: 'West African CFA Franc', symbol: 'Fr' },
        { code: 'XPF', name: 'CFP Franc', symbol: 'Fr' },
        { code: 'YER', name: 'Yemeni Rial', symbol: '﷼' },
        { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
        { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
        { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '$' }
    ],

    languages: [
        { code: 'AR', name: 'Arabic', nativeName: 'العربية' },
        { code: 'BG', name: 'Bulgarian', nativeName: 'български' },
        { code: 'CA', name: 'Catalan', nativeName: 'Català' },
        { code: 'CS', name: 'Czech', nativeName: 'Čeština' },
        { code: 'DA', name: 'Danish', nativeName: 'Dansk' },
        { code: 'DE', name: 'German', nativeName: 'Deutsch' },
        { code: 'EL', name: 'Greek', nativeName: 'Ελληνικά' },
        { code: 'EN', name: 'English', nativeName: 'English' },
        { code: 'ES', name: 'Spanish', nativeName: 'Español' },
        { code: 'ET', name: 'Estonian', nativeName: 'Eesti' },
        { code: 'FI', name: 'Finnish', nativeName: 'Suomi' },
        { code: 'FR', name: 'French', nativeName: 'Français' },
        { code: 'HE', name: 'Hebrew', nativeName: 'עברית' },
        { code: 'HI', name: 'Hindi', nativeName: 'हिन्दी' },
        { code: 'HR', name: 'Croatian', nativeName: 'Hrvatski' },
        { code: 'HU', name: 'Hungarian', nativeName: 'Magyar' },
        { code: 'ID', name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
        { code: 'IS', name: 'Icelandic', nativeName: 'Íslenska' },
        { code: 'IT', name: 'Italian', nativeName: 'Italiano' },
        { code: 'JA', name: 'Japanese', nativeName: '日本語' },
        { code: 'KO', name: 'Korean', nativeName: '한국어' },
        { code: 'LT', name: 'Lithuanian', nativeName: 'Lietuvių' },
        { code: 'LV', name: 'Latvian', nativeName: 'Latviešu' },
        { code: 'MT', name: 'Maltese', nativeName: 'Malti' },
        { code: 'NL', name: 'Dutch', nativeName: 'Nederlands' },
        { code: 'NO', name: 'Norwegian', nativeName: 'Norsk' },
        { code: 'PL', name: 'Polish', nativeName: 'Polski' },
        { code: 'PT', name: 'Portuguese', nativeName: 'Português' },
        { code: 'RO', name: 'Romanian', nativeName: 'Română' },
        { code: 'RU', name: 'Russian', nativeName: 'Русский' },
        { code: 'SK', name: 'Slovak', nativeName: 'Slovenčina' },
        { code: 'SL', name: 'Slovenian', nativeName: 'Slovenščina' },
        { code: 'SV', name: 'Swedish', nativeName: 'Svenska' },
        { code: 'TH', name: 'Thai', nativeName: 'ไทย' },
        { code: 'TR', name: 'Turkish', nativeName: 'Türkçe' },
        { code: 'UK', name: 'Ukrainian', nativeName: 'Українська' },
        { code: 'VI', name: 'Vietnamese', nativeName: 'Tiếng Việt' },
        { code: 'ZH', name: 'Chinese', nativeName: '中文' }
    ]
};

// Helper functions to get data
function getCountries() {
    return referenceData.countries.sort((a, b) => a.name.localeCompare(b.name));
}

function getCurrencies() {
    return referenceData.currencies.sort((a, b) => a.code.localeCompare(b.code));
}

function getLanguages() {
    return referenceData.languages.sort((a, b) => a.name.localeCompare(b.name));
}

function getCountryByCode(code) {
    return referenceData.countries.find(country => country.code === code);
}

function getCurrencyByCode(code) {
    return referenceData.currencies.find(currency => currency.code === code);
}

function getLanguageByCode(code) {
    return referenceData.languages.find(language => language.code === code);
}

// Make functions globally available
if (typeof window !== 'undefined') {
    window.referenceData = {
        getCountries,
        getCurrencies,
        getLanguages,
        getCountryByCode,
        getCurrencyByCode,
        getLanguageByCode
    };
}

// Export for Node.js if needed
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        referenceData,
        getCountries,
        getCurrencies,
        getLanguages,
        getCountryByCode,
        getCurrencyByCode,
        getLanguageByCode
    };
}